env: local
port: 8895
metric_port: 2113
mysql:
  base:
    master_dsn: admin:boomstage88888888@tcp(database-2.cdeq6yiysgml.us-east-2.rds.amazonaws.com:3306)/boomstage?timeout=30s&charset=utf8mb4&interpolateParams=true
    slave_dsn: admin:boomstage88888888@tcp(database-2.cdeq6yiysgml.us-east-2.rds.amazonaws.com:3306)/boomstage?timeout=30s&charset=utf8mb4&interpolateParams=true
  admin:
    dsn: admin:boomstage88888888@tcp(database-2.cdeq6yiysgml.us-east-2.rds.amazonaws.com:3306)/boomstage?timeout=30s&charset=utf8mb4&interpolateParams=true
redis:
  addr: 127.0.0.1:6379
  password: ""
jwt:
  secrets:
    0: "gosh-secret"
    1: "gosh_admin-secret"
file:
  s3:
    access_key_id: AKIAQE43KARW4PKHRSDZ
    secret_access_key: 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
    bucket: gosh-static-test
  cdn:
    domain: https://static-test.gosh0.com
cdn:
  domain: https://static-test.gosh0.com
lark:
  app_id: cli_a6540d48def9d010
  app_secret: hJRzIpeetzdK1uhDQ3PzRbh5RIe6VSqq
aws:
  access_key_id: AKIAQE43KARW4PKHRSDZ
  secret_access_key: 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
  bucket: gosh-static-test